### ISSUE TITLE
writing a value overrides all values in the bucket

### ISSUE THREAD

**Issue by nickgeudens** [Nike-Inc/cerberus-cli#12]
When I try to write a value using:
`cerberus-cli --url='...' --region='us-west-2' secret write ${sdbPath} -e ${sdbKey}='value'`
it puts the secret in the right place. but removes al the rest.

If I look at the code you parse every entry as one json and than apply that json to the bucket. Is it possible to just create/update that one entry?

**Comment by shawn-sher** [comment]
The latest version will now accept a --merge flag to leave the other keys alone.
