### ISSUE TITLE
How does Authentication work?

### ISSUE THREAD

**Issue by kyeotic** [Nike-Inc/cerberus-cli#17]
Pardon my ignorance, but the [Authentication](https://github.com/Nike-Inc/cerberus-cli#authentication) section of the readme doesn't actually explain how authentication works or how to configure it.

* Does it use the default aws creds?
* Is it possible to control which role is used, if several are available?
* is it possible to control which profile is used, if several are available?
* Can the aws role/creds be passed into the CLI as arguments? Environment variables?

**Comment by shawn-sher** [comment]
These answers are included in the README,. Whatever works for the SDK works for the cli.
This document (linked in the README) explains it in some detail: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html
